name: planner
description: Restaurant Helper planner package
publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=3.2.2'

dependencies:
  flutter:
    sdk: flutter
  utils:
    path: '../utils'
  auth:
    path: '../auth'
  font_awesome_flutter: ^10.3.0
  dio: ^5.2.0
  rounded_loading_button: ^2.1.0
  shared_preferences: ^2.2.0
  hooks_riverpod: ^2.1.3
  freezed_annotation: ^2.2.0
  riverpod_annotation:
  flutter_dotenv: ^5.1.0
  json_annotation: ^4.8.1
  fluttertoast: ^8.2.4
  flutter_hooks: ^0.20.3
  url_launcher: ^6.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  freezed: ^2.3.2
  build_runner: ^2.3.3
  riverpod_generator:
  riverpod_lint: ^2.3.7
  custom_lint: ^0.5.7
  json_serializable: ^6.6.2
  
flutter:
  uses-material-design: true
